---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://raw.githubusercontent.com/devantler-tech/kyverno-policies/752a288171a6a26331e0a33ac18132ead0718cd3/policies/best-practices/add-recommended-labels.yaml
