---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/
  - ../../../bases/infrastructure/coroot/
components:
  - ../../../components/observability-coroot/allow-host-access/
  - ../../../components/observability-coroot/remove-opencost-references/
