---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/
  - ../../../bases/infrastructure/coroot/
components:
  - ../../../components/helmrelease-flux-defaults/
  - ../../../components/helmrelease-drift-detection/
  - ../../../components/observability-coroot/allow-host-access/
  - ../../../components/observability-coroot/isolate-heartbeat/
  - ../../../components/observability-coroot/remove-opencost-references/
  - ../../../components/observability-coroot/remove-kps-ui/
