---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seed-alertmanager
  namespace: flux-system
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: variables-cluster
  data:
    - match:
        secretKey: alertmanager_webhook_url
        remoteRef:
          remoteKey: infrastructure/monitoring/alertmanager
          property: webhook_url
