---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seed-cloudflare
  namespace: flux-system
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: variables-base
  data:
    - match:
        secretKey: cloudflare_api_token
        remoteRef:
          remoteKey: infrastructure/dns/cloudflare
          property: api_token
