---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-dex-client-secret
  namespace: openbao
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: dex-client-secret
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: infrastructure/oidc/dex
          property: client-secret
