---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seed-github-app
  namespace: flux-system
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: variables-cluster
  data:
    - match:
        secretKey: github_app_client_secret
        remoteRef:
          remoteKey: infrastructure/oidc/github
          property: client-secret
