---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-proxy-config
  namespace: oauth2-proxy
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":8080"
    providers:
      file:
        filename: /etc/traefik/dynamic.yaml
    log:
      level: INFO
  dynamic.yaml: |
    http:
      routers:
        homepage:
          rule: "Host(`${domain}`)"
          entryPoints: ["web"]
          service: homepage
        hubble:
          rule: "Host(`hubble.${domain}`)"
          entryPoints: ["web"]
          service: hubble-ui
        prometheus:
          rule: "Host(`prometheus.${domain}`)"
          entryPoints: ["web"]
          service: prometheus
        alertmanager:
          rule: "Host(`alertmanager.${domain}`)"
          entryPoints: ["web"]
          service: alertmanager
        opencost:
          rule: "Host(`opencost.${domain}`)"
          entryPoints: ["web"]
          service: opencost
      services:
        homepage:
          loadBalancer:
            servers:
              - url: "http://homepage.homepage.svc.cluster.local:80"
        hubble-ui:
          loadBalancer:
            servers:
              - url: "http://keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local:8080"
        prometheus:
          loadBalancer:
            servers:
              - url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
        alertmanager:
          loadBalancer:
            servers:
              - url: "http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"
        opencost:
          loadBalancer:
            servers:
              - url: "http://opencost.opencost.svc.cluster.local:9090"
