---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/apps/
patches:
  - target:
      kind: HelmRelease
      name: headlamp
      namespace: headlamp
    path: headlamp/patches/helm-release-patch.yaml
