apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 2m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  test:
    enable: false
  chart:
    spec:
      chart: vpa
      version: 4.11.0
      sourceRef:
        kind: HelmRepository
        name: vertical-pod-autoscaler
  # https://github.com/FairwindsOps/charts/blob/master/stable/vpa/values.yaml
  values:
    recommender:
      replicaCount: ${vpa_recommender_replicas:=1}
      podSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    updater:
      enabled: true
      replicaCount: ${vpa_updater_replicas:=1}
      podSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    admissionController:
      replicaCount: ${vpa_admission_replicas:=2}
      podSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      podDisruptionBudget:
        minAvailable: 1
