---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - flux-kustomization-bootstrap.yaml
  - flux-kustomization-infrastructure-controllers.yaml
  - flux-kustomization-infrastructure.yaml
  - flux-kustomization-apps.yaml


