---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-meta.yaml
  - bootstrap-flux-kustomization.yaml
  - infrastructure-controllers-flux-kustomization.yaml
  - infrastructure-flux-kustomization.yaml
  - apps-flux-kustomization.yaml


