---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/controllers/
  - ../../../bases/infrastructure/controllers/coroot/
components:
  - ../../../components/observability-coroot/disable-watchdog/
  - ../../../components/observability-coroot/remove-controllers-loki-alloy/
  - ../../../components/observability-coroot/remove-controller-opencost/
  - ../../../components/observability-coroot/remove-opencost-references/
