apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - http-route-grafana.yaml
  - http-route-prometheus.yaml
  - http-route-alertmanager.yaml
  - cilium-network-policy.yaml
