apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 2m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  chart:
    spec:
      chart: external-dns
      version: 1.21.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    provider:
      name: cloudflare
    sources:
      - gateway-httproute
    policy: sync
    registry: txt
    txtOwnerId: "${domain}"
    txtPrefix: "_externaldns."
    domainFilters:
      - "${cloudflare_zone}"
    extraArgs:
      - --exclude-target-net=10.0.0.0/8
      - --cloudflare-proxied
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: api-token
    deploymentStrategy:
      type: Recreate
    serviceMonitor:
      enabled: false
