apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - persistent-volume-claim.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - http-route.yaml
  - http-scaled-object.yaml
  - cilium-network-policy.yaml
