apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - httproute.yaml
  - http-scaled-object.yaml
  - networkpolicy.yaml
