apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  dependsOn:
    - name: cert-manager
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: trust-manager
      version: v0.22.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  # https://artifacthub.io/packages/helm/cert-manager/trust-manager
  values:
    crds:
      enabled: true
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    replicaCount: ${trust_manager_replicas:=2}
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: trust-manager
            app.kubernetes.io/instance: trust-manager
