---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alerts/
  - certificates/
  - cluster-policies/
  - cluster-role-bindings/
  - cluster-roles/
  - cluster-secret-stores/
  - external-secrets/
  - gateway/
  - http-scaled-objects/
  - security-exceptions/
  - tracing-policies/
  - vault-config/
  - vault-backup/
  - vault-seed/
