---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod/
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: infrastructure-controllers
      namespace: flux-system
    patch: |
      - op: test
        path: /spec/path
        value: providers/hetzner/infrastructure/controllers
      - op: replace
        path: /spec/path
        value: providers/hetzner/infrastructure-controllers-coroot
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: infrastructure
      namespace: flux-system
    patch: |
      - op: test
        path: /spec/path
        value: providers/hetzner/infrastructure
      - op: replace
        path: /spec/path
        value: providers/hetzner/infrastructure-coroot
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: apps
      namespace: flux-system
    patch: |
      - op: test
        path: /spec/path
        value: providers/hetzner/apps
      - op: replace
        path: /spec/path
        value: providers/hetzner/apps-coroot
