apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 2m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  chart:
    spec:
      chart: keda
      version: 2.19.0
      sourceRef:
        kind: HelmRepository
        name: keda
  # https://github.com/kedacore/charts/blob/main/keda/values.yaml
  values:
    crds:
      install: true
    operator:
      replicaCount: ${keda_operator_replicas:=1}
    webhooks:
      replicaCount: ${keda_webhooks_replicas:=1}
